// GENERATED by scripts/build-model-sources.mjs — do not edit by hand.
// Every model file the engine installer can fetch: official URL, size (bytes), SHA-256, license.
export const MODEL_FAMILIES = [
    {
        "id": "zimage",
        "label": "Z-Image Turbo",
        "what": "Pictures from words or a picture",
        "kind": "image",
        "variants": {
            "int8": [
                {
                    "folder": "diffusion_models",
                    "name": "z_image_turbo_int8_convrot.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/diffusion_models/z_image_turbo_int8_convrot.safetensors",
                    "size": 6201001296,
                    "sha256": "be517ebd47c912a5626a588e1aeea43e6be4a43c0cdcd2b48a2a780d9f358635",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/z_image_turbo"
                    }
                },
                {
                    "folder": "text_encoders",
                    "name": "qwen_3_4b_fp8_mixed.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/text_encoders/qwen_3_4b_fp8_mixed.safetensors",
                    "size": 5631994051,
                    "sha256": "72450b19758172c5a7273cf7de729d1c17e7f434a104a00167624cba94f68f15",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/z_image_turbo"
                    }
                },
                {
                    "folder": "vae",
                    "name": "ae.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/vae/ae.safetensors",
                    "size": 335304388,
                    "sha256": "afc8e28272cd15db3919bacdb6918ce9c1ed22e96cb12c4d5ed0fba823529e38",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/z_image_turbo"
                    }
                }
            ],
            "bf16": [
                {
                    "folder": "diffusion_models",
                    "name": "z_image_turbo_bf16.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/diffusion_models/z_image_turbo_bf16.safetensors",
                    "size": 12309866400,
                    "sha256": "2407613050b809ffdff18a4ac99af83ea6b95443ecebdf80e064a79c825574a6",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/z_image_turbo"
                    }
                },
                {
                    "folder": "text_encoders",
                    "name": "qwen_3_4b.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/text_encoders/qwen_3_4b.safetensors",
                    "size": 8044982048,
                    "sha256": "6c671498573ac2f7a5501502ccce8d2b08ea6ca2f661c458e708f36b36edfc5a",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/z_image_turbo"
                    }
                },
                {
                    "folder": "vae",
                    "name": "ae.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/vae/ae.safetensors",
                    "size": 335304388,
                    "sha256": "afc8e28272cd15db3919bacdb6918ce9c1ed22e96cb12c4d5ed0fba823529e38",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/z_image_turbo"
                    }
                }
            ]
        }
    },
    {
        "id": "ltx",
        "label": "LTX-2.3 Distilled",
        "what": "Video with sound, fast",
        "kind": "video",
        "variants": {
            "distilled-fp8": [
                {
                    "folder": "checkpoints",
                    "name": "ltx-2.3-22b-distilled-fp8.safetensors",
                    "url": "https://huggingface.co/Lightricks/LTX-2.3-fp8/resolve/main/ltx-2.3-22b-distilled-fp8.safetensors",
                    "size": 29531884062,
                    "sha256": "d9646b6f2d5c42d337b23671634c43bfeece6989644f51b4a3aa088465ccd3b2",
                    "license": {
                        "name": "ltx-2-community-license-agreement",
                        "link": "https://github.com/Lightricks/LTX-2/blob/main/LICENSE"
                    }
                },
                {
                    "folder": "text_encoders",
                    "name": "gemma_3_12B_it_fp4_mixed.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/ltx-2/resolve/main/split_files/text_encoders/gemma_3_12B_it_fp4_mixed.safetensors",
                    "size": 9447702218,
                    "sha256": "aaca463d11e6d8d2a4bdb0d6299214c15ef78a3f73e0ef8113d5a9d0219b3f6d",
                    "license": {
                        "name": "ltx-2-community-license-agreement",
                        "link": "https://github.com/Lightricks/LTX-2/blob/main/LICENSE"
                    }
                }
            ]
        }
    },
    {
        "id": "h3",
        "label": "MiniMax-H3 Turbo",
        "what": "Video with sound, best quality",
        "kind": "video",
        "variants": {
            "int8": [
                {
                    "folder": "diffusion_models",
                    "name": "minimax_h3_fl2va_pruned_int8_convrot.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/diffusion_models/minimax_h3_fl2va_pruned_int8_convrot.safetensors",
                    "size": 20970379616,
                    "sha256": "e889202c41dafb67b10d67b97f0d8541508036a6090af23425a5c2615d03c47a",
                    "license": {
                        "name": "minimax-h3-community-license-agreement",
                        "link": "https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE"
                    }
                },
                {
                    "folder": "text_encoders",
                    "name": "qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/text_encoders/qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors",
                    "size": 15687142551,
                    "sha256": "35a88d51044231fe332301d7a62aa81e3f2cba62febeb446e2c1e3e0ef76f2c6",
                    "license": {
                        "name": "minimax-h3-community-license-agreement",
                        "link": "https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE"
                    }
                },
                {
                    "folder": "vae",
                    "name": "minimax_h3_video_vae_int8_convrot.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/vae/minimax_h3_video_vae_int8_convrot.safetensors",
                    "size": 2811065184,
                    "sha256": "52a2c8c73583c86e4f41cdcce3a6ad0ea562987bc0bf3d60a0cef5f5c8e60c0e",
                    "license": {
                        "name": "minimax-h3-community-license-agreement",
                        "link": "https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE"
                    }
                },
                {
                    "folder": "vae",
                    "name": "minimax_h3_audio_vae_fp32.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/vae/minimax_h3_audio_vae_fp32.safetensors",
                    "size": 605254808,
                    "sha256": "8e505d95dd1561d47abd43d4238fd40d9bb1ae9e147ed0a4cba778d76ae4db48",
                    "license": {
                        "name": "minimax-h3-community-license-agreement",
                        "link": "https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE"
                    }
                },
                {
                    "folder": "loras",
                    "name": "minimax_h3_fl2v_turbo_4step_v1.0_768p_comfyui_bf16.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/loras/minimax_h3_fl2v_turbo_4step_v1.0_768p_comfyui_bf16.safetensors",
                    "size": 1956192992,
                    "sha256": "c396a9a06f58399e9df9754b18299818d84a2ddd371724ba48fe4a41221437dc",
                    "license": {
                        "name": "minimax-h3-community-license-agreement",
                        "link": "https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE"
                    }
                }
            ]
        }
    },
    {
        "id": "wan5b",
        "label": "Wan 2.2 5B",
        "what": "Silent draft video, light",
        "kind": "video",
        "variants": {
            "fp16": [
                {
                    "folder": "diffusion_models",
                    "name": "wan2.2_ti2v_5B_fp16.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors",
                    "size": 9999658848,
                    "sha256": "456f901338bd9eadbded3828b819109a9b68e8a525ca5cf8d0049a69fcfeca1e",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged"
                    }
                },
                {
                    "folder": "text_encoders",
                    "name": "umt5_xxl_fp8_e4m3fn_scaled.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors",
                    "size": 6735906897,
                    "sha256": "c3355d30191f1f066b26d93fba017ae9809dce6c627dda5f6a66eaa651204f68",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged"
                    }
                },
                {
                    "folder": "vae",
                    "name": "wan2.2_vae.safetensors",
                    "url": "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan2.2_vae.safetensors",
                    "size": 1409400960,
                    "sha256": "e40321bd36b9709991dae2530eb4ac303dd168276980d3e9bc4b6e2b75fed156",
                    "license": {
                        "name": "apache-2.0",
                        "link": "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged"
                    }
                }
            ]
        }
    }
];
