// One-off port of bloop's hangar icon set (the owner's own drawings) into src/shared/icons.js.
// Company logos (icon-maker-*) are trademarks and are deliberately NOT ported.
// Usage: node scripts/port-icons.mjs "\\wsl.localhost\ubuntu-26.04\home\jo\Projects\bloop\resources\views\icon"
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const sourceDir = process.argv[2];
if (!sourceDir) throw new Error('Pass the bloop icon folder.');

const PLATE = 'M2 3.25 H14 V10.4 L11.4 13 H2 Z';
const icons = {
    // From bloop's mode-icon: the three channels.
    image: `<path d="${PLATE}"/><path d="M3.6 11 L6.6 7.6 L8.8 9.9"/><circle cx="10.7" cy="6.1" r="0.95" fill="currentColor" stroke="none"/>`,
    video: `<path d="${PLATE}"/><path d="M6.6 5.9 L10.6 8.15 L6.6 10.4 Z" fill="currentColor" stroke-width="1"/>`,
    text: '<path d="M2.4 4.2 H13.6"/><path d="M2.4 7.4 H13.6"/><path d="M2.4 10.6 H9.2"/>',
    // New, drawn to the same rules (16 grid, 1.5 stroke, square caps, mitred, cut corners).
    sun: '<path d="M5.5 5.5 H10.5 V9.5 L9.5 10.5 H5.5 Z"/><path d="M8 1.25 V3 M8 13 V14.75 M1.25 8 H3 M13 8 H14.75 M3 3 L4.25 4.25 M11.75 11.75 L13 13 M13 3 L11.75 4.25 M3 13 L4.25 11.75"/>',
    moon: '<path d="M10.5 1.75 L6 1.75 L2.75 5 V11 L5 13.25 H11 L14.25 10 V9 L12 11.25 H7.5 L5.25 9 V4.75 Z"/>',
    undo: '<path d="M5 3 L2.25 5.75 L5 8.5"/><path d="M2.75 5.75 H10.5 L13.25 8.5 V10.5 L10.5 13.25 H6"/>',
    redo: '<path d="M11 3 L13.75 5.75 L11 8.5"/><path d="M13.25 5.75 H5.5 L2.75 8.5 V10.5 L5.5 13.25 H10"/>',
    minus: '<path d="M2.75 8 H13.25"/>',
    bolt: '<path d="M9.5 1.5 L3.5 9 H8 L6.5 14.5 L12.5 7 H8 Z"/>',
    settings: '<path d="M6.75 1.75 H9.25 L9.75 3.5 L11.25 4.25 L12.9 3.5 L14.25 5.75 L12.9 7 V9 L14.25 10.25 L12.9 12.5 L11.25 11.75 L9.75 12.5 L9.25 14.25 H6.75 L6.25 12.5 L4.75 11.75 L3.1 12.5 L1.75 10.25 L3.1 9 V7 L1.75 5.75 L3.1 3.5 L4.75 4.25 L6.25 3.5 Z"/><path d="M6.5 6.5 H9.5 V9.5 H6.5 Z"/>',
    note: '<path d="M2.75 2.75 H13.25 V9.75 L9.75 13.25 H2.75 Z"/><path d="M9.75 13.25 V9.75 H13.25"/><path d="M5 5.5 H11 M5 8 H8.5"/>',
};

for (const file of readdirSync(sourceDir).sort()) {
    const match = file.match(/^icon-([a-z0-9-]+)\.blade\.php$/);
    if (!match || match[1].startsWith('maker') || icons[match[1]]) continue;
    // Strip Blade comments AND echoes first: `{{ $attributes->merge(...) }}` sits inside the <svg>
    // tag, and its `->` would otherwise end the tag match early and leak Blade code into the icon.
    const source = readFileSync(join(sourceDir, file), 'utf8')
        .replace(/\{\{--[\s\S]*?--\}\}/g, '')
        .replace(/\{\{[\s\S]*?\}\}/g, '')
        .replace(/rotate\(\s+/g, 'rotate(0 '); // a stripped direction echo: default orientation (right)
    const inner = source.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
    if (!inner) {
        console.warn(`skipped ${file}: no inline <svg> drawing`);
        continue;
    }
    icons[match[1]] = inner[1].replace(/\s+/g, ' ').replace(/>\s+</g, '><').trim();
}

const body = Object.entries(icons)
    .map(([name, svg]) => `    '${name}': '${svg.replace(/'/g, "\\'")}',`)
    .join('\n');

writeFileSync(new URL('../src/shared/icons.js', import.meta.url), `// GENERATED by scripts/port-icons.mjs from bloop's hangar icon set (the owner's own drawings),
// plus a few new glyphs drawn to the same rules. Company logos are intentionally excluded.
// 16-unit grid, 1.5 stroke, square caps, mitred joins, currentColor: icons follow the theme.
export const ICONS = {
${body}
};

const ATTRS = 'viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" stroke-linejoin="miter" aria-hidden="true" focusable="false"';

/** Inline SVG markup for an icon (empty string if unknown, never a broken image). */
export function icon(name, className = 'ae-icon') {
    const inner = ICONS[name];
    return inner ? \`<svg class="\${className}" width="1em" height="1em" \${ATTRS}>\${inner}</svg>\` : '';
}
`);

console.log(`ported ${Object.keys(icons).length} icons`);
